version: "3.9"
services:
  mongo:
    image: 'mongo:latest'
    restart: always
    platform: linux/x86_64
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      MONGO_USERNAME: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PWD}
      MONGO_URL: 'mongodb://mongo:27017'
    depends_on:
      - mongo
