openapi: 3.1.0
info:
  title: GitHub Actions stat collector
  version: 1.0.0

paths:
  /ping:
    get:
      responses:
        '200':
          description: Pong
  /api/v1/timing:
    post:
      security:
        - bearerAuth:
          - 'read:users'
          - 'public'
      requestBody:
        description: Test
        required: true
        content:
          applicatoin/json:
            schema:
              $ref: '#/components/schemas/ActionLogEntry'
        responses:
          '200':
            description: Updated
          '201':
            description: Created
    get:
      security:
        - bearerAuth:
          - 'read:users'
          - 'public'
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: ActionLogEntry name. If empty provides all names 
        - in: query
          name: start
          schema:
            type: string
          description: ActionLogEntry start time. If empty provides all starting dates.
            Input in format [lt|lte|eq|gte|gt]<HH:MM:SS DD-MM-YYYY>
        - in: query
          name: end 
          schema:
            type: string
          description: ActionLogEntry end time. If empty provides all ending dates.
            Input in format [lt|lte|eq|gte|gt]<HH:MM:SS DD-MM-YYYY>
        - in: query
          name: successful
          schema:
            type: bool
          description: If ActionLogEntry was successful. If empty provides all entries.
        - in: query
          name: arch
          schema:
            type: array
            items: string
          description: Arch of runners for specific ActionLogEntry. If empty provides all entries.
        - in: query
          name: perpage
          schema:
            type: integer
          description: Number of object displayed per page. If not provided will use default value
        - in: query
          name: page
          schema:
            type: integer
            description: Number of page to access. If not provided will show first page
      responses:
        '200':
          description: List of ActionLogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActionLogEntrySearch'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
      description: 'note: non-oauth scopes are not defined at the securityScheme level'
  schemas:
    StepLogEntry:
      title: Step log entry
      type: object
      properties:
        id:
          type: string
          description: Number of the step 
        exec_time:
          type: uint64
          description: Time took to execute step
        successful:
          type: bool
          description: Was step successful
    ActionLogEntry:
      title: Action log entry 
      type: object
      properties:
        name:
          type: string
          description: Name of the action. Uses GITHUB_ACTION environment variable
        start:
          type: string
          description: Start of the action
        end:
          type: string
          description: End of the action
        successful:
          type: bool
          description: Was action successful
        arch:
          type: string
          description: Arch of runner
          enum: [X86, X64, ARM, ARM64]
        steps:
          type: array
          items:
            - $ref: "#/components/schemas/StepEntry"
      required:
        - name
        - start
        - end
        - successful
        - arch
    ActionLogEntrySearch:
      title: ActionLogEntry objects returning from search
      type: object
      properties:
        perPage:
          type: integer
          description: Number of ActionLogEntry objects per page
        totalPages:
          type: integer
          description: Number of total pages
        curPage:
          type: integer
          description: Current page number
        data:
          type: array
          description: ActionLog Objects
          items:
            - $ref: "#/components/schemas/ActionLogEntry"


